import { expect, test } from '@playwright/test';
import { auditPage, visit } from './fixtures/audit';

/**
 * The written summary, end to end — everything except the model call.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * WHAT THIS CAN AND CANNOT PROVE, STATED BEFORE THE ASSERTIONS
 *
 * There is no `ANTHROPIC_API_KEY` in this environment, so `modelClient()` returns null
 * and the action stops one step before the network. That sounds like it makes the test
 * worthless. It does not, and the reason is worth writing down: **everything on this side
 * of the call is the part with a database in it.** The capability check, the centre flag,
 * the month boundary computed in the centre's timezone, the spend read, `checkSpend`, and
 * the insert into `ai_requests` all run against live Postgres under a real JWT, with RLS
 * in front of them. The model call is the one step that is pure network.
 *
 * So this covers the blocked path completely and the successful path not at all, which is
 * the honest split. `unverified-claims` §27 records the other half.
 *
 * A second thing it proves that no unit test can: that the panel is **absent** until a
 * centre turns it on. `ai_features` defaults false, and a feature that appeared by default
 * would be a cross-border disclosure control that defaults to open.
 */

/** Save the settings form and wait for the action to land, not merely dispatch. */
async function save(page: import('@playwright/test').Page) {
  const done = page.waitForResponse(
    (r) => new URL(r.url()).pathname === '/settings' && r.request().method() === 'POST',
  );
  await page.getByRole('button', { name: 'Save' }).click();
  await done;
}

const TOGGLE = 'Let this centre use written summaries generated by Anthropic’s Claude';

test('the summary panel is absent until a centre turns it on, and refuses honestly once it is', async ({
  page,
}) => {
  // ---------------------------------------------------------------- off by default
  await visit(page, '/compliance');
  await expect(page.getByRole('heading', { name: 'Written summary' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Write a summary' })).toHaveCount(0);

  // ---------------------------------------------------------------- turn it on
  await visit(page, '/settings');
  const toggle = page.getByLabel(TOGGLE);
  await expect(toggle).not.toBeChecked();
  await toggle.check();
  await save(page);

  /*
    Asserted before moving on, for the reason 0048 exists: `centres` carries COLUMN-level
    UPDATE grants, and a column missing from that list makes Postgres refuse the whole
    statement — which silently breaks every other field on this form rather than this one.
    Reading the value back is how that failure announces itself.
  */
  await page.reload({ waitUntil: 'networkidle' });
  await expect(page.getByLabel(TOGGLE)).toBeChecked();

  // ---------------------------------------------------------------- now it appears
  await visit(page, '/compliance');
  await expect(page.getByRole('heading', { name: 'Written summary' })).toBeVisible();

  /*
    Scoped to the panel, not to the page. A bare `getByRole('alert')` matches Next's
    `__next-route-announcer__`, which is an empty live region present on every route — so
    the query resolved to two elements and Playwright refused it in strict mode. Scoping
    keeps the assertion going through the ARIA role, which is the contract worth testing,
    rather than dropping to a CSS class to dodge the collision.
  */
  const panel = page
    .locator('.card')
    .filter({ has: page.getByRole('heading', { name: 'Written summary' }) });

  const button = panel.getByRole('button', { name: 'Write a summary' });
  await expect(button).toBeVisible();
  await button.click();

  /*
    No key on this deployment, so the action records a `blocked` row and returns a
    sentence. The assertion is on the sentence a manager would read, not on an internal
    status — and specifically that it does NOT say the centre has run out of an allowance,
    which is the wrong message and the one `checkSpend`'s ordering exists to prevent.
  */
  const alert = panel.getByRole('alert');
  await expect(alert).toBeVisible();
  await expect(alert).toContainText('not available on this deployment');
  await expect(alert).not.toContainText('monthly limit');

  // Nothing was presented as a finding, because nothing was produced.
  await expect(page.getByText('Draft — not a compliance finding')).toHaveCount(0);

  /*
    AUDITED HERE BECAUSE IT CANNOT BE AUDITED ANYWHERE ELSE.

    `a11y.spec.ts` sweeps every staff screen, but it sees `/compliance` with `ai_features`
    off — which is the default and the state that page is in for the whole of that suite.
    So this panel would have shipped as the one piece of UI no accessibility audit had ever
    looked at, and the gap would have been invisible: the sweep would keep reporting
    `/compliance` as clean, truthfully, about a version of the page without this on it.

    Run in the error state on purpose: the `role="alert"` live region is the part most
    likely to be wrong, and it does not exist until a click has failed.

    What this does NOT cover, stated so nobody assumes otherwise: the pending state. By
    the time the assertions above have settled, `useTransition` has finished and the
    button is enabled again, so the disabled-while-writing markup is never audited. It
    would need a request the test can hold open, which is not available without a key.
  */
  await auditPage(page, '/compliance with the written summary panel');

  // ---------------------------------------------------------------- put it back
  await visit(page, '/settings');
  await page.getByLabel(TOGGLE).uncheck();
  await save(page);
  await page.reload({ waitUntil: 'networkidle' });
  await expect(page.getByLabel(TOGGLE)).not.toBeChecked();
});
