/**
 * Point Supabase Auth at the deployed application, and close the gaps its defaults leave.
 *
 * WHY THIS IS A SCRIPT AND NOT A DASHBOARD VISIT
 *
 * Because two of these settings decide where a link in somebody's email takes them, and one
 * decides how short a password may be. Configuration that only ever existed as a sequence of
 * clicks cannot be reviewed, cannot be repeated on a second project, and cannot be restored
 * after somebody changes it "to test something".
 *
 * WHAT IT SETS, AND WHY EACH ONE MATTERS
 *
 * `site_url` and `uri_allow_list` — as at 2026-08-05 the project pointed at
 * `http://localhost:3000`, which is correct for development and wrong the moment anything is
 * deployed. Every invitation and password-reset link this product issues is generated by
 * GoTrue and lands on `site_url`, so until this is changed a real staff member clicks their
 * invitation and their browser tries to open a server on their own laptop. The allow-list is
 * the other half: a redirect target that is not on it is silently replaced with `site_url`.
 *
 * `password_min_length` — the project allowed **six**. The invitation form in this app
 * refuses anything under ten, with a comment about NIST dropping composition rules, so the
 * product has been promising a stronger minimum than the service enforced. Anything that
 * sets a password by another route — a recovery link, the dashboard, a future screen — was
 * held to six. The app's own rule and the service's rule now agree, and the service is the
 * one that cannot be bypassed.
 *
 * WHAT IT DELIBERATELY LEAVES ALONE
 *
 * `disable_signup` is already `true` and stays that way: there is no public sign-up in this
 * product and there must not be, because an account is how somebody reaches children's
 * records. `mailer_autoconfirm` stays `true` — the invitation token was sent to the mailbox
 * and nowhere else, so it has already proved the address, and requiring a second
 * confirmation email from a project with no configured mailer would block onboarding
 * entirely. MFA enrolment stays enabled even though no screen uses it yet; it costs nothing
 * and removing it would have to be undone later.
 *
 *   npm run deploy:auth -- --domain https://ece-production.up.railway.app
 *   npm run deploy:auth                      # hardening only, no URL change
 *   npm run deploy:auth -- --dry-run --domain https://…
 */

interface AuthConfig {
  site_url?: string;
  uri_allow_list?: string;
  password_min_length?: number;
  disable_signup?: boolean;
  mailer_autoconfirm?: boolean;
}

/** The app's own minimum, in `apps/web/src/lib/password.ts`. Kept in step deliberately. */
const APP_PASSWORD_MIN = 10;

function die(message: string): never {
  console.error(`\n  ${message}\n`);
  process.exit(1);
}

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const domainIndex = args.indexOf('--domain');
  const domainArg = domainIndex >= 0 ? args[domainIndex + 1] : undefined;

  const token = process.env.SUPABASE_ACCESS_TOKEN;
  const ref = process.env.SUPABASE_PROJECT_REF;
  if (!token || !ref) die('SUPABASE_ACCESS_TOKEN and SUPABASE_PROJECT_REF are required.');

  let origin: string | null = null;
  if (domainArg) {
    let parsed: URL;
    try {
      parsed = new URL(domainArg);
    } catch {
      die(`--domain must be an absolute URL, e.g. https://ece.up.railway.app — got "${domainArg}"`);
    }
    // http would mean auth cookies over plaintext, and the app sends HSTS.
    if (parsed.protocol !== 'https:') die('--domain must be https.');
    /*
     * THE PATH IS KEPT, AND IT USED TO BE THROWN AWAY.
     *
     * This was `parsed.origin`, which drops everything after the host. That was correct
     * while the console was the only thing on its hostname, and became wrong the moment it
     * was mounted under a path: Doorway has no domain of its own, so it is served at
     * `/portal` on the Little Pearls website's hostname with `basePath` set to match.
     *
     * With the path discarded, `site_url` would have been the bare host — and **every
     * invitation and password-reset link in this product lands on `site_url`**. So a new
     * kaiako would click their invitation and arrive at the marketing homepage, with the
     * token fragment attached to a page that has no idea what to do with it. The failure
     * looks like a broken email rather than a missing path segment, and nothing in the app
     * would have logged a thing.
     *
     * The allow-list below inherits the path too, which is a tightening rather than a side
     * effect: a redirect target outside the console has no business being permitted.
     */
    origin = (parsed.origin + parsed.pathname).replace(/\/+$/, '');
  }

  const base = `https://api.supabase.com/v1/projects/${ref}/config/auth`;
  const headers = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' };

  const before = await fetch(base, { headers });
  if (!before.ok) die(`Reading the auth config failed: ${(await before.text()).slice(0, 300)}`);
  const current = (await before.json()) as AuthConfig;

  console.log('\n  Supabase auth configuration');
  console.log(`  project ${ref}\n`);
  console.log('  before:');
  console.log(`    site_url             ${JSON.stringify(current.site_url)}`);
  console.log(`    uri_allow_list       ${JSON.stringify(current.uri_allow_list)}`);
  console.log(`    password_min_length  ${current.password_min_length}`);
  console.log(`    disable_signup       ${current.disable_signup}`);

  const patch: AuthConfig = {};

  if (current.password_min_length !== APP_PASSWORD_MIN) {
    patch.password_min_length = APP_PASSWORD_MIN;
  }

  if (origin) {
    patch.site_url = origin;
    // The Expo scheme stays: the mobile app's deep links go through it, and dropping it
    // would break password recovery on a device without any error a user could act on.
    // localhost stays too, because development still has to work — and this list is an
    // allowlist of *redirect targets*, not of who may sign in.
    patch.uri_allow_list = [
      origin,
      `${origin}/**`,
      'http://localhost:3000',
      'http://localhost:3000/**',
      'exp://**',
    ].join(',');
  }

  if (Object.keys(patch).length === 0) {
    console.log('\n  Nothing to change.\n');
    return;
  }

  console.log('\n  change:');
  for (const [k, v] of Object.entries(patch)) console.log(`    ${k.padEnd(20)} ${JSON.stringify(v)}`);

  if (dryRun) {
    console.log('\n  --dry-run, nothing sent.\n');
    return;
  }

  const res = await fetch(base, { method: 'PATCH', headers, body: JSON.stringify(patch) });
  if (!res.ok) die(`Updating the auth config failed: ${(await res.text()).slice(0, 400)}`);

  const after = (await res.json()) as AuthConfig;
  console.log('\n  after:');
  console.log(`    site_url             ${JSON.stringify(after.site_url)}`);
  console.log(`    uri_allow_list       ${JSON.stringify(after.uri_allow_list)}`);
  console.log(`    password_min_length  ${after.password_min_length}`);

  if (origin) {
    console.log(
      '\n  Invitation and recovery links now land on the deployed app. Any link issued\n' +
        '  before this change still points at the old site_url — reissue them.',
    );
  }
  console.log('');
}

main().catch((e) => die(e instanceof Error ? e.message : String(e)));
